name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install kind
        uses: helm/kind-action@v1.5.0
      - name: install kubectl
        uses: azure/setup-kubectl@v2.1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Login GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCRIO }}
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: build
        run: |
          export TZ='Asia/Shanghai'
          export PATH=$PATH:$(go env GOPATH)/bin
          # make static
          # make build
          make docker
